"""Minimal passive execution graph and relation contracts."""

from .capabilities import is_row_partitionable
from .graph import ExecutionGraph, GraphInputSpec, NodeSpec, OutputSpec
from .operations import (
    ExpandOp,
    FilterByMaskOp,
    FilterOp,
    KeyJoinSpec,
    MapOp,
    OperationSpec,
    OperatorFactorySpec,
    ReduceOp,
    RelateOp,
    RelationAdapterSpec,
    operation_name,
)
from .policy import (
    IsolationBudget,
    IsolationExhaustedAction,
    RecordRecoveryAction,
    RecoveryPolicy,
    RetryTiming,
    ShardExhaustedAction,
    ShardRecoveryAction,
    WorkerPoolSpec,
)
from .refs import GraphInputRef, NodeOutputRef, PortRef
from .relations import (
    AggregateOf,
    ChildrenOf,
    IncompleteGroupPolicy,
    OutputRelation,
    RelatedFrom,
    RoleSource,
    SameAs,
    SubsetOf,
)
from .verify import GraphValidationError, validate_shard_plan, verify_graph

__all__ = [
    "AggregateOf",
    "ChildrenOf",
    "ExecutionGraph",
    "ExpandOp",
    "FilterByMaskOp",
    "FilterOp",
    "GraphInputRef",
    "GraphInputSpec",
    "GraphValidationError",
    "IncompleteGroupPolicy",
    "IsolationBudget",
    "IsolationExhaustedAction",
    "KeyJoinSpec",
    "MapOp",
    "NodeOutputRef",
    "NodeSpec",
    "OperationSpec",
    "OperatorFactorySpec",
    "OutputRelation",
    "OutputSpec",
    "PortRef",
    "RecordRecoveryAction",
    "RecoveryPolicy",
    "ReduceOp",
    "RelateOp",
    "RelatedFrom",
    "RelationAdapterSpec",
    "RetryTiming",
    "RoleSource",
    "SameAs",
    "ShardExhaustedAction",
    "ShardRecoveryAction",
    "SubsetOf",
    "WorkerPoolSpec",
    "is_row_partitionable",
    "operation_name",
    "validate_shard_plan",
    "verify_graph",
]
